<template>
  <div>
    <p>tabsDemo</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
    <p>switch</p>
  </div>
</template>